n = input('Digite um valor qualquer: ')
print('Este valor é numérico?')
print(n.isnumeric())
print('Este valor é alfanumerico?')
print(n.isalnum())
print('Esta valor é alfabético?')
print(n.isalpha())
print('Este valor está em caixa alta?')
print(n.isupper())
print('Este valor está em caixa baixa? ')
print(n.islower())